services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fintech-api
    ports:
      - "8080:2026"
    environment:
      PORT: 2026
      JWT_SECRET: your-secret
      MONGO_URI: mongodb://mongo:27017/fintech_dashboard
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    container_name: fintech-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: fintech-mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: